<?php

return [
    'summarize' => [
        'icon' => 'fa fa-align-left',
        'prompt' => 'Summarize the following text:' . "\r\n\r\n" . '%s',
        'single_input' => true,
        'input_icon' => 'fa fa-paragraph',
    ],
    'explain_for_a_kid' => [
        'icon' => 'fa fa-child',
        'prompt' => 'Explain & summarize the following text like I am 5: %s',
        'single_input' => true,
        'input_icon' => 'fa fa-paragraph',
    ],
    'spinner' => [
        'icon' => 'fa fa-sync',
        'prompt' => 'Rewrite the following text in a different manner:' . "\r\n\r\n" . '%s',
        'single_input' => true,
        'input_icon' => 'fa fa-paragraph',
    ],
    'keywords_generator' => [
        'icon' => 'fa fa-key',
        'prompt' => 'Extract important keywords from:' . "\r\n\r\n" . '%s',
        'single_input' => true,
        'input_icon' => 'fa fa-paragraph',
    ],
    'grammar_fixer' => [
        'icon' => 'fa fa-spell-check',
        'prompt' => 'Fix the grammar on the following:' . "\r\n\r\n" . '%s',
        'single_input' => true,
        'input_icon' => 'fa fa-paragraph',
    ],
    'social_bio' => [
        'icon' => 'fa fa-share-alt',
        'prompt' => 'Write a short social media bio profile description based on those keywords: %s',
        'single_input' => true,
        'input_icon' => 'fa fa-file-word',
    ],
    'seo_title' => [
        'icon' => 'fa fa-heading',
        'prompt' => 'Write an SEO Title for a web page based on those keywords: %s',
        'single_input' => true,
        'input_icon' => 'fa fa-file-word',
    ],
    'seo_description' => [
        'icon' => 'fa fa-pen',
        'prompt' => 'Write an SEO description, maximum 160 characters, for a web page based on the following: %s',
        'single_input' => true,
        'input_icon' => 'fa fa-paragraph',
    ],
    'seo_keywords' => [
        'icon' => 'fa fa-file-word',
        'prompt' => 'Write SEO meta keywords, maximum 160 characters, for a web page based on the following: %s',
        'single_input' => true,
        'input_icon' => 'fa fa-paragraph',
    ],
    'blog_article_idea_and_outline' => [
        'icon' => 'fa fa-blog',
        'prompt' => 'Write ideas for a blog article title and outline, based on the following: %s',
        'single_input' => true,
        'input_icon' => 'fa fa-paragraph',
    ],
    'blog_article_section' => [
        'icon' => 'fa fa-rss',
        'prompt' => 'Write a blog sections about: %s' . "\r\n" . 'Keywords: %s',
        'single_input' => false,
    ],
    'video_idea' => [
        'icon' => 'fa fa-video',
        'prompt' => 'Write ideas for a video scenario, based on the following: %s',
        'single_input' => true,
        'input_icon' => 'fa fa-paragraph',
    ],
    'video_title' => [
        'icon' => 'fa fa-play',
        'prompt' => 'Write a video title, based on the following: %s',
        'single_input' => true,
        'input_icon' => 'fa fa-paragraph',
    ],
    'video_description' => [
        'icon' => 'fa fa-film',
        'prompt' => 'Write a video description, based on the following: %s',
        'single_input' => true,
        'input_icon' => 'fa fa-paragraph',
    ],
    'ad_title' => [
        'icon' => 'fa fa-money-check-alt',
        'prompt' => 'Write a short ad title, based on the following: %s',
        'single_input' => true,
        'input_icon' => 'fa fa-paragraph',
    ],
    'ad_description' => [
        'icon' => 'fa fa-th-list',
        'prompt' => 'Write a short ad description, based on the following: %s',
        'single_input' => true,
        'input_icon' => 'fa fa-paragraph',
    ],
    'text_to_emoji' => [
        'icon' => 'fa fa-smile-wink',
        'prompt' => 'Transform the following text into emojis: %s',
        'single_input' => true,
        'input_icon' => 'fa fa-paragraph',
    ],
    'tweet' => [
        'icon' => 'fab fa-twitter',
        'prompt' => 'Generate a tweet based on the following text/keywords: %s',
        'single_input' => true,
        'input_icon' => 'fa fa-paragraph',
    ],
    'instagram_caption' => [
        'icon' => 'fab fa-instagram',
        'prompt' => 'Generate an instagram caption for a post based on the following text/keywords: %s',
        'single_input' => true,
        'input_icon' => 'fa fa-paragraph',
    ],
    'name_generator' => [
        'icon' => 'fa fa-file-signature',
        'prompt' => 'Generate multiple & relevant product names based on the following text/keywords: %s',
        'single_input' => true,
        'input_icon' => 'fa fa-paragraph',
    ],
    'startup_ideas' => [
        'icon' => 'fa fa-user-tie',
        'prompt' => 'Generate multiple & relevant startup business ideas based on the following text/keywords: %s',
        'single_input' => true,
        'input_icon' => 'fa fa-paragraph',
    ],
    'viral_ideas' => [
        'icon' => 'fa fa-bolt',
        'prompt' => 'Generate a viral idea based on the following text/keywords: %s',
        'single_input' => true,
        'input_icon' => 'fa fa-paragraph',
    ],
    'custom' => [
        'icon' => 'fa fa-star',
        'prompt' => '%s',
        'single_input' => true,
        'input_icon' => 'fa fa-paragraph',
    ],
];
